tests: omit tag argument in dbg_d macro in tst-bsd-tcp1.cc
Without this change, building the tests in `mode=debug` (where
`CONF_logger_debug` is set) fails with the following error with
GCC >= 11:

	error: too few arguments to function ‘int printf(const char*, ...)’
		#define dbg_d(tag, ...) printf(__VA_ARGS__)

This commit fixes that by removing the tag argument as the macro
is only used with a single argument in the code.