boost: add missing library
When cross-compiling boost on CentOS 7 for aarch64, there is a library missing
from the list of boost libraries. Steps to reproduce were:

  $ source scripts/download_aarch64_toolchain.sh
  $ CROSS_PREFIX=aarch64-none-linux-gnu- scripts/download_and_build_boost.sh 1.72.0 aarch64
  $ scripts/build arch=aarch64 fs=rofs --create-disk image=tests -j12

The failure observed was:

...
  IMGEDIT build/release.aarch64/loader.img
Writing image
Adding /libenviron.so
Adding /libvdso.so
Adding /tools/mount-fs.so
Adding /tools/umount.so
Adding /usr/lib/libgcc_s.so.1
Adding /usr/lib/libtest_simple.so
Adding /usr/lib/libtest_empty.so
Adding /usr/lib/libtest_dlsym_from_this_grandchild.so
Adding /usr/lib/libtest_dlsym_from_this_child.so
Adding /usr/lib/libtest_dlsym_from_this.so
Adding /usr/lib/libdlext_test.so
Adding /usr/lib/libtest_with_dependency.so
Adding /usr/lib/libtest_check_rtld_next_from_library.so
Adding /usr/lib/libboost_system.so.1.72.0
Traceback (most recent call last):
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 369, in <module>
    main()
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 366, in main
    gen_image(outfile, manifest)
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 269, in gen_image
    system_structure_block, bytes_written = write_fs(fp, manifest)
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 246, in write_fs
    count, directory_entries_index = write_dir(fp, manifest.get(''), '', manifest)
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 207, in write_dir
    count, directory_entries_index = write_dir(fp, val, dirpath + '/' + entry, manifest)
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 207, in write_dir
    count, directory_entries_index = write_dir(fp, val, dirpath + '/' + entry, manifest)
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 222, in write_dir
    inode.count = write_file(fp, val)
  File "/home/stew/osv/scripts/gen-rofs-img.py", line 164, in write_file
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/stew/osv/build/downloaded_packages/aarch64/boost/upstream/boost_1_72_0/stage/lib/libboost_timer.so'
scripts/build failed: "$SRC"/scripts/gen-rofs-img.py -o rofs.img -m usr.manifest -D libgcc_s_dir="$libgcc_s_dir"

Signed-off-by: Stewart Hildebrand <stewart.hildebrand@dornerworks.com>
Message-Id: <20210316180734.127045-1-stewart.hildebrand@dornerworks.com>